name: build
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      -
        name: Build testing container
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.development_builder.outputs.name }}
          load: true
          tags: fitbit-http-php-testing:latest
      -
        name: Run tests
        uses: addnab/docker-run-action@v1
        with:
          image: fitbit-http-php-testing:latest
          shell: sh
          run: vendor/bin/phpunit --coverage-clover clover.xml
